classic: false

blocks:
  - permission
  - size
  - date
  - git
  - name

color:
  when: auto
  theme: custom

date: date

dereference: false

icons:
  when: never
  theme: fancy
  separator: " "

indicators: true

layout: grid

recursion:
  enabled: false
size: default

permission: rwx

sorting:
  column: name
  reverse: false
  dir-grouping: none

no-symlink: false

total-size: false

hyperlink: never

symlink-arrow: =>

header: false
